### ISSUE TITLE
add user-defined option in cli integration tests

### ISSUE THREAD

**Issue by mirageoasis** [lablup/backend.ai#1957]
while working on 

#1778 

I ran through error that if --pyargs option comes user defined option gets deleted

And I figured out why!

which means we can independently run test using pytest soley!

[Link](https://github.com/pytest-dev/pytest/issues/1596)

in this link it states that conftest.py should be located under folder of testpaths which means we have to fix 

testpahts option under `pyproject.toml`
from
```toml
testpaths = "tests"
markers = [
    "integration: Test cases that spawn Dockerized kernel sessions",
]
filterwarnings = [
    "ignore::DeprecationWarning:etcd3.*:",
]
asyncio_mode = "auto"
```

to

```
testpaths = [
    "tests",
    "src/ai/backend/test"
]
markers = [
    "integration: Test cases that spawn Dockerized kernel sessions",
]
filterwarnings = [
    "ignore::DeprecationWarning:etcd3.*:",
]
asyncio_mode = "auto"
```
