### ISSUE TITLE
Task template

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#70]
Let's make the parameter sets for batch sessions (#42) to be reusable and referrable by task graph API (#43).

A template should include:
 - The kernel image
 - Resource specification
 - The batch command to execute
 - The vfolder mounts
 - Bootstrap script (encoded as base64) → #77 
 - Timeout (maybe infinite)
 - Git repository auto-clone parameters (repo URL, credentials, target commit/branch)

A template can be used in the following contexts:
 - Just run a single session using the template
 - Run a task graph composed of multiple, staged tasks from multiple templates
   - In this case, each session will have `/home/work/input` and `/home/work/output` directories which are auto-created vfolders by the smanager for the input/output connection between different stages.
   - It may also have the task sequence number as a special environment variable so that each task may determine the partition of input data to process or the parameters to use with its computation, for parallelized tasks in the same stage.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159751085623729/1159757050611348) by [Unito](https://www.unito.io/learn-more)

**Comment by kyujin-cho** [comment]
Initial design of the template:
```yaml
---
apiVersion: v1
kind: session
metadata:
  sessionId: mysession-01
  tag: example-tag
spec:
  kernels:
  - image: python:3.6-ubuntu18.04
    environ:
      MYCONFIG: XXX
    run:
      bootstrap: IyEvYmluL3NoCmNkICRIT01FCm1rZGlyIHRtcDEKZWNobyAiMTIzNDUiID4gdG1wMQoK
      batch:
        build: gcc -Wall main.c -o main -lrt -lz
        exec: ./main
    mounts:
      mydata: /home/work/somepath
      mypkgs: 
    resources:
      cpu: 2
      mem: 4g
      cuda.devices: 1
    git:
      repository: https://github.com/lablup/backend.ai-agent
      commit: 10daee9e328876d75e6d0fa4998d4456711730db 
      branch: 19.09
      credential:
        username: lablup
        password: qwerty1234
```
